# Generated by Django 6.0.4 on 2026-04-26 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemadmin', '0002_remove_systemsetting_updated_at_and_more'),
        ('trains', '0003_schedule_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train_conductors', to='systemadmin.company'),
        ),
        migrations.AddField(
            model_name='route',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train_routes', to='systemadmin.company'),
        ),
        migrations.AddField(
            model_name='train',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trains', to='systemadmin.company'),
        ),
    ]
