# Generated by Django 6.0.4 on 2026-04-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0004_conductor_company_route_company_train_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='business_seats',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='train',
            name='economy_seats',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddField(
            model_name='train',
            name='first_class_seats',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
