# Generated by Django 5.2.14 on 2026-05-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0006_booking_booking_reference_booking_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per ticket for this route', max_digits=10),
        ),
        migrations.AddField(
            model_name='train',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the train (visible to passengers)', null=True),
        ),
    ]
