# Generated by Django 5.2.14 on 2026-06-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0010_route_business_price_route_economy_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='parcel_base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base parcel shipping price for this route', max_digits=10),
        ),
    ]
