# Generated by Django 5.2.1 on 2026-04-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('bus_admin', 'Bus Admin'), ('train_admin', 'Train Admin'), ('flight_admin', 'Flight Admin'), ('driver', 'Driver'), ('passenger', 'Passenger')], max_length=20),
        ),
    ]
