# Generated by Django 5.2.1 on 2026-05-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('bus_admin', 'Bus Admin'), ('train_admin', 'Train Admin'), ('flight_admin', 'Flight Admin'), ('driver', 'Driver'), ('passenger', 'Passenger')], default='passenger', max_length=20),
        ),
    ]
