# Generated by Django 5.2.14 on 2026-05-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('bus_admin', 'Bus Admin'), ('train_admin', 'Train Admin'), ('flight_admin', 'Flight Admin'), ('driver', 'Driver'), ('technical_staff', 'Technical Staff'), ('passenger', 'Passenger')], default='passenger', max_length=20),
        ),
    ]
