# Generated by Django 5.2.14 on 2026-05-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='assigned_vehicle_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='assigned_vehicle_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='parcel',
            name='assigned_vehicle_type',
            field=models.CharField(blank=True, help_text='bus/train/flight', max_length=10, null=True),
        ),
    ]
