# Generated by Django 5.2.14 on 2026-06-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_parcel_assigned_vehicle_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='parcel_images/'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='recipient_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='parcel',
            name='sender_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
