# Generated by Django 6.0.4 on 2026-04-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemadmin', '0002_remove_systemsetting_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatLayoutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('bus', 'Bus'), ('train', 'Train'), ('flight', 'Flight')], max_length=20)),
                ('vehicle_id', models.PositiveIntegerField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('layout', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
