# Generated by Django 5.2.14 on 2026-05-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemadmin', '0003_seatlayouthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Company logo/image (visible to passengers)', null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, help_text='Overall description of the company (visible to passengers)'),
        ),
    ]
