# Generated by Django 5.2.14 on 2026-05-26 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemadmin', '0005_subscriber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first_class', 'First Class'), ('vip', 'VIP'), ('normal', 'Normal'), ('executive', 'Executive'), ('sleeper', 'Sleeper')], max_length=50)),
                ('transport_type', models.CharField(choices=[('bus', 'Bus'), ('train', 'Train'), ('flight', 'Flight')], max_length=20)),
                ('display_name', models.CharField(help_text='Display name for passengers', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('color_code', models.CharField(default='#2ecc71', help_text='Hex color for seat display', max_length=20)),
                ('icon', models.CharField(default='seat', help_text='Icon class or emoji', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['transport_type', 'name'],
                'unique_together': {('name', 'transport_type')},
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('bus', 'Bus'), ('train', 'Train'), ('flight', 'Flight')], max_length=20)),
                ('vehicle_id', models.PositiveIntegerField()),
                ('seat_number', models.CharField(help_text="e.g., '1A', 'A-01', '12'", max_length=20)),
                ('seat_row', models.PositiveIntegerField(help_text='Row number')),
                ('seat_column', models.CharField(help_text='Column letter (A, B, C, etc.)', max_length=10)),
                ('cabin_id', models.CharField(blank=True, help_text='Cabin/Coach identifier', max_length=50)),
                ('cabin_name', models.CharField(blank=True, help_text='Cabin/Coach name', max_length=100)),
                ('position_x', models.PositiveIntegerField(help_text='X coordinate for UI rendering')),
                ('position_y', models.PositiveIntegerField(help_text='Y coordinate for UI rendering')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_extra_legroom', models.BooleanField(default=False)),
                ('is_window', models.BooleanField(default=False)),
                ('is_aisle', models.BooleanField(default=False)),
                ('is_emergency_exit_row', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('reserved', 'Reserved/Held'), ('blocked', 'Blocked/Unavailable')], default='available', max_length=20)),
                ('held_until', models.DateTimeField(blank=True, help_text='Reservation hold expiration time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('held_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_seats', to=settings.AUTH_USER_MODEL)),
                ('seat_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seats', to='systemadmin.seatclass')),
            ],
            options={
                'ordering': ['seat_row', 'seat_column'],
            },
        ),
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_token', models.CharField(help_text='Unique token for this hold', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active Hold'), ('confirmed', 'Confirmed (Booking Created)'), ('released', 'Released'), ('expired', 'Expired')], default='active', max_length=20)),
                ('hold_duration_minutes', models.PositiveIntegerField(default=10, help_text='Minutes to hold seat')),
                ('held_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('travel_date', models.DateField()),
                ('travel_time', models.TimeField(blank=True, null=True)),
                ('release_reason', models.CharField(blank=True, help_text='Why the reservation was released', max_length=200)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='systemadmin.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-held_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('bus', 'Bus'), ('train', 'Train'), ('flight', 'Flight')], max_length=20)),
                ('template_name', models.CharField(help_text="e.g., 'Dreamline VIP', '49-Seater Standard'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('total_seats', models.PositiveIntegerField()),
                ('rows', models.PositiveIntegerField(help_text='Number of rows')),
                ('columns', models.PositiveIntegerField(help_text='Number of columns')),
                ('aisle_position', models.PositiveIntegerField(default=1, help_text='Column index where aisle is located')),
                ('aisle_arrangement', models.CharField(choices=[('2x2', '2×2 (2 columns, 1 aisle)'), ('2x1_vip', '2×1 VIP (2 on left, 1 on right)'), ('3x2', '3×2 (3 columns, 1 aisle, 2 columns)'), ('3x3', '3×3 (3 columns, 1 aisle, 3 columns)'), ('sleeper', 'Sleeper (2 levels)'), ('custom', 'Custom Layout')], default='2x2', max_length=50)),
                ('has_driver_cockpit', models.BooleanField(default=True)),
                ('driver_location', models.CharField(default='front', help_text="'front', 'left', 'right'", max_length=20)),
                ('has_doors', models.PositiveIntegerField(default=2, help_text='Number of doors')),
                ('door_locations', models.JSONField(blank=True, default=list, help_text="Door positions: [{'position': 'front', 'side': 'left'}]")),
                ('cabins', models.JSONField(blank=True, default=list, help_text="Cabin info: [{'name': 'Cabin A', 'seats': 60, 'class': 'first_class'}]")),
                ('emergency_exits', models.PositiveIntegerField(default=0)),
                ('galley_location', models.CharField(blank=True, help_text='Galley location on aircraft', max_length=50)),
                ('lavatory_locations', models.JSONField(blank=True, default=list, help_text='Lavatory positions')),
                ('layout_data', models.JSONField(blank=True, default=dict, help_text='Complete seat layout configuration')),
                ('is_template', models.BooleanField(default=True, help_text='Reusable template flag')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_layouts', to='systemadmin.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_layouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('bus', 'Bus'), ('train', 'Train'), ('flight', 'Flight')], max_length=20)),
                ('booking_id', models.PositiveIntegerField()),
                ('booking_reference', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('passenger_name', models.CharField(max_length=255)),
                ('passenger_phone', models.CharField(blank=True, max_length=50)),
                ('passenger_id', models.CharField(blank=True, help_text='Passport/ID for verification', max_length=50)),
                ('is_checked_in', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.CharField(blank=True, help_text='QR code data', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_checkins', to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='systemadmin.seat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['booking_reference'], name='systemadmin_booking_af87c7_idx'), models.Index(fields=['status'], name='systemadmin_status_de5c87_idx')],
                'unique_together': {('seat', 'booking_id', 'content_type')},
            },
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['content_type', 'vehicle_id', 'status'], name='systemadmin_content_eefb65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('content_type', 'vehicle_id', 'seat_number')},
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['user', 'status'], name='systemadmin_user_id_ddae4e_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['expires_at'], name='systemadmin_expires_270880_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclelayout',
            unique_together={('company', 'template_name', 'vehicle_type')},
        ),
    ]
