# Generated by Django 5.2.14 on 2026-06-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('cash', 'Cash'), ('cod', 'Pay on Delivery'), ('loyalty', 'Loyalty Points')], default='mpesa', max_length=10),
        ),
    ]
