# Generated by Django 6.0.4 on 2026-04-26 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_schedule_price'),
        ('systemadmin', '0002_remove_systemsetting_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='systemadmin.company'),
        ),
        migrations.AddField(
            model_name='pilot',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_pilots', to='systemadmin.company'),
        ),
        migrations.AddField(
            model_name='route',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_routes', to='systemadmin.company'),
        ),
    ]
