# Generated by Django 6.0.4 on 2026-04-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_flight_company_pilot_company_route_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='business_seats',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='flight',
            name='economy_seats',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='first_class_seats',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
