# Generated by Django 5.2.14 on 2026-05-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_flight_description_route_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_cargo',
            field=models.BooleanField(default=False, help_text='Mark this vehicle as cargo only (not visible to passenger bookings)'),
        ),
    ]
