# Generated by Django 5.2.14 on 2026-05-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_flight_is_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='boarded',
            field=models.BooleanField(default=False),
        ),
    ]
