# Generated by Django 5.2.14 on 2026-05-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_booking_boarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='business_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Price for business class seats on this route', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='economy_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Price for economy class seats on this route', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='first_class_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Price for first class seats on this route', max_digits=10, null=True),
        ),
    ]
