# Generated by Django 5.2.14 on 2026-06-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0011_route_parcel_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='other_destinations',
            field=models.JSONField(blank=True, default=list, help_text='Optional intermediate stop locations for this route.'),
        ),
    ]
