# Generated by Django 6.0.4 on 2026-04-26 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_schedule_price'),
        ('systemadmin', '0002_remove_systemsetting_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='systemadmin.company'),
        ),
        migrations.AddField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_drivers', to='systemadmin.company'),
        ),
        migrations.AddField(
            model_name='route',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_routes', to='systemadmin.company'),
        ),
    ]
