# Generated by Django 6.0.4 on 2026-04-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0005_bus_company_driver_company_route_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='normal_seats',
            field=models.PositiveIntegerField(default=35),
        ),
        migrations.AddField(
            model_name='bus',
            name='vip_seats',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
