# Generated by Django 5.2.14 on 2026-05-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0007_booking_booking_reference_booking_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the bus (visible to passengers)', null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='number_plate',
            field=models.CharField(blank=True, help_text='Vehicle registration number plate', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per ticket for this route', max_digits=10),
        ),
    ]
