# Generated by Django 5.2.14 on 2026-05-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0008_bus_description_bus_number_plate_route_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='is_cargo',
            field=models.BooleanField(default=False, help_text='Mark this vehicle as cargo only (not visible to passenger bookings)'),
        ),
    ]
