# Generated by Django 5.2.14 on 2026-05-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0010_booking_boarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='normal_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Price for normal seats on this route', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='vip_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Price for VIP seats on this route', max_digits=10, null=True),
        ),
    ]
